### ISSUE TITLE
installtion with curl and bashsript does not work

### ISSUE THREAD

**Issue by streulch** [relnod/dotm#26]
While using a linux on a stick (Arch, Manjaro) follwing output is generatet:
sh <(curl https://raw.githubusercontent.com/relnod/dotm/master/install.sh) --user
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-- 100  1475  100  1475    0     0  13915      0 --:--:-- --:--:-- --:--:-- 13915
Downloading dotm binary at version v0.2.0
Installing dotm to /home/manjaro/.local/bin
Generating bash completions at /home/manjaro/.bash_completion.d
/dev/fd/63: line 58: dotm: command not found

**Comment by relnod** [comment]
The problem is  that `/home/manjaro/.local/bin` is not in your `$PATH`. 
See https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#Home%20Directory for more info about the user specify bin directory.

To fix it, you can put the following in your shell configuration:
```bash
export PATH="$PATH:$HOME/.local/bin"
```
